---
title: "My Portfolio"
---

This website hosts my [portfolio](https://datascience4psych.github.io/DataScience4Psych/guidance.html#portfolio) and [accompanying documentation](https://datascience4psych.github.io/DataScience4Psych/guidance.html#documenting-your-project) that I developed as part of [Data Science for Psychologists](https://datascience4psych.github.io/DataScience4Psych/). You can find the links to individual portfolio pieces in the header. Each piece has a description of the goal, the product (computer program, hand graph, computer graph, etc.), the data, and some interpretation. I encourage you to explore them.

### Portfolio 1: Math-ing in R 

### Portfolio 2: Correlation Matrix, Scatter Plot Matrix, and Network Plots

### Portfolio 3: ACE Modeling with Simulated Data & EasyMx

### Portfolio 4: Shiny App Interactive Dashboard 

### Portfolio 5: Survival Analysis 

### Portfolio 6: Factor Analysis with the NLSY 

### Portfolio 7: Making FYP Poster Figures 

### Portfolio 8: Love is Blind Plot Recreation 

### Portfolio 9: Dog Cards

### Portfolio 10: Airline Loyalty Data - Data Wrangling Practice

